### ISSUE TITLE
error C2664: 'HRESULT

### ISSUE THREAD

**Issue by johnjohnsp1** [trevorsaudi/Mshikaki#4]
Hi,
thanks for sharing the code, i followed your instruction about the compile step but getting this error:

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.8.1
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Windows\System32>cd \temp

C:\temp>cd Mshikaki

C:\temp\Mshikaki>cl /EHsc Mshikaki.cpp /link /SUBSYSTEM:CONSOLE
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33130 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

Mshikaki.cpp
Mshikaki.cpp(72): error C2664: 'HRESULT URLDownloadToFileA(LPUNKNOWN,LPCSTR,LPCSTR,DWORD,LPBINDSTATUSCALLBACK)': cannot convert argument 2 from 'const wchar_t *' to 'LPCSTR'
Mshikaki.cpp(72): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um\urlmon.h(5016): note: see declaration of 'URLDownloadToFileA'
Mshikaki.cpp(72): note: while trying to match the argument list '(int, const wchar_t *, const wchar_t *, int, int)'
Mshikaki.cpp(79): warning C4305: 'return': truncation from 'int' to 'bool'

anything i miss or do wrong ?
thanks in advice

**Comment by trevorsaudi** [comment]
Thanks for pointing it out! This has been fixed in the latest commit. Much appreciated!
